<?php

namespace AppBundle\Repository;

/**
 * Etudiant_PFERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etudiant_PFERepository extends \Doctrine\ORM\EntityRepository
{
}
