<?php

namespace AppBundle\Repository;

/**
 * Etudiant_EnseignantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etudiant_EnseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
