<?php

namespace AppBundle\Repository;

/**
 * PfeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfeRepository extends \Doctrine\ORM\EntityRepository
{
}
