etudiants : 
  type: rest
  resource:     "AppBundle:Etudiant"
  name_prefix:  api_

enseignants : 
  type: rest
  resource:     "AppBundle:Enseignant"
  name_prefix:  api_
entreprises : 
  type: rest
  resource:     "AppBundle:Entreprise"
  name_prefix:  api_
users : 
  type: rest
  resource:     "AppBundle:User"
  name_prefix:  api_