AppBundle\Entity\Etudiant_Enseignant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Etudiant_EnseignantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idEtd:
            type: integer
            column: id_etd
        idEns:
            type: integer
            column: id_ens
        date:
            type: date
    lifecycleCallbacks: {  }
